# Generated by Django 4.0.3 on 2022-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseFee', models.FloatField(null=True)),
                ('courseTeacher', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
